data_root:
  # KITTI sequences root
#  data_root_folder: "/home/mjy/datasets/overlapnet_datasets/OverlapNet/kitti/dataset_full/"
  data_root_folder: "/home/vectr/PycharmProjects/overlap_transformer/kitti_dataset/kitti_seq_root/"
  # KITTI sequence 02 velodyne
#  valid_scan_folder: "/home/mjy/datasets/kitti/02/velodyne"
  valid_scan_folder: "/home/vectr/PycharmProjects/overlap_transformer/kitti_dataset/kitti_seq_root/02"
  # KITTI sequence 02 computed overlaps
#  gt_valid_folder: "/home/mjy/dev/OverlapNet++/kittiHandler/computed_overlap/"
  gt_valid_folder: "/home/vectr/PycharmProjects/overlap_transformer/kitti_dataset/computed_overlap_02/"

demo1_config:
  # calibration file from KITTI 00
#  calib_file: "/home/mjy/datasets/kitti/data_odometry_calib/dataset/sequences/00/calib.txt"
  calib_file: "/home/vectr/PycharmProjects/overlap_transformer/kitti_dataset/calib.txt"
  # pose file from KITTI 00
#  poses_file: "/home/mjy/datasets/kitti/data_odometry_poses/dataset/poses/00.txt"
  poses_file: "/home/vectr/PycharmProjects/overlap_transformer/kitti_dataset/00.txt"
  # pretrained model
#  test_weights: "/home/mjy/dev/OverlapTransformer/weights/pretrained_overlap_transformer.pth.tar"
  test_weights: "/home/vectr/PycharmProjects/overlap_transformer/kitti_dataset/pretrained_overlap_transformer.pth.tar"

training_config:
  # KITTI sequences for training
  training_seqs: ["03", "04", "05","06", "07", "08", "09"]

test_config:
  # KITTI sequence 00 for evaluation
  test_seqs: ["00"]
  # pretrained model
  test_weights: "/home/mjy/dev/OverlapTransformer/weights/pretrained_overlap_transformer.pth.tar"
  # ground truth
  gt_file: "/home/mjy/dev/OverlapNet++/kittiHandler/overlapnet_test00_methods/loop_gt_seq00_0.3overlap_inactive.npz"

viz_config:
  # calibration file from KITTI 00
  calib_file: "/home/mjy/datasets/kitti/data_odometry_calib/dataset/sequences/00/calib.txt"
  # pose file from KITTI 00
  poses_file: "/home/mjy/datasets/kitti/data_odometry_poses/dataset/poses/00.txt"
  # covariance file from SUMA++ on KITTI 00
  cov_file: "/home/mjy/dev/OverlapNet++/kittiHandler/overlapnet_test00_methods/covariance_2nd.txt"
